apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ddns
  name: ddns
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ddns
  template:
    metadata:
      labels:
        app: ddns
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: Exists
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
      - image: crazymax/ddns-route53:2.14.0
        name: ddns-route53
        env:
          - name: TZ
            value: Asia/Ho_Chi_Minh
          - name: SCHEDULE
            value: "*/5 * * * *"
          - name: LOG_LEVEL
            value: info
          - name: LOG_JSON
            value: "false"
          - name: DDNSR53_CREDENTIALS_ACCESSKEYID
            valueFrom:
              secretKeyRef:
                name: ddns-route53
                key: AWS_ACCESS_KEY_ID
          - name: DDNSR53_CREDENTIALS_SECRETACCESSKEY
            valueFrom:
              secretKeyRef:
                name: ddns-route53
                key: AWS_SECRET_ACCESS_KEY
          - name: DDNSR53_ROUTE53_HOSTEDZONEID
            valueFrom:
              secretKeyRef:
                name: ddns-route53
                key: HOSTED_ZONE_ID
          - name: DDNSR53_ROUTE53_RECORDSSET_0_NAME
            value: sso.tylerops.dev.
          - name: DDNSR53_ROUTE53_RECORDSSET_0_TYPE
            value: A
          - name: DDNSR53_ROUTE53_RECORDSSET_0_TTL
            value: "300"
        resources: 
          requests:
            cpu: "10m"
            memory: "16Mi"
          limits:
            cpu: "50m"
            memory: "32Mi"
