apiVersion: v1
kind: Secret
metadata:
    name: ddns-route53
    namespace: kube-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:wio4vluG4NcS+f/yT4849lJleZM=,iv:LtUBBxUU/c4NHYvZ5iTxJWPkEQpwlpPNbk7lTTwtRkE=,tag:a7WMbcaniPxPP1sJx/5LHA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:R5FPE40M2LxMgPLt5m9Sx4QWTMJrVDmEzVIDpc4AT2jbE0dptDhDUA==,iv:c24QuJMZhynnQAVxcfTadz76b1SMhRl8CLCXqs2gBkA=,tag:7RwF/KGD3TEBtDY7Tj9NYA==,type:str]
    HOSTED_ZONE_ID: ENC[AES256_GCM,data:jkTGp3FLT9AtCUHlLqBquk7ZCsg=,iv:vmyiMDoQauJymn+4ucZiC/9gboiFSFN9XRoDu0vDS5Y=,tag:6DhhXANLvYNXQajRNhep2w==,type:str]
sops:
    age:
        - recipient: age1ngzn99y6lskxmkvlt2zpfcdwpfhk6dgwpkp7f39t5tplk4nrf40s7k826s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQ3ZENkdBMnV5YWpCS2E5
            SGR4M011S3NTZ0ZOa0pYZjJjZStHZysrSlh3CmJ6L0x0UVd0REhqSmcyTnhteXZT
            OVdKN00zNlhvZ0VrYkZrWUc1aGJ0eGMKLS0tIEhjYzRrM0Q3T1E1ZHNvbTlpQnRT
            eGlEb05kRmY4NTl3dWRFWXo1bGpMbG8K6oSyV/Ra8Gr/VGcaXk++i0nMPsbPR8JU
            7uxb9+/EOtO4YchG8kZ37FRh/Ywb0zhab7SehTtzQVqVaFXvyz489w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T01:14:22Z"
    mac: ENC[AES256_GCM,data:1ozoC/DEU+nym7gBQ0efglGRWnalO1PzT0MQB1EpfZm6GOc+xMuRogpB9VMhe8P+i1GYJ7u4kBWxz6fUT2M0Dxe/Q3EbLbKfcr3pf7WjMJkSVoFsXEb9LvDoGmijkartrqHU6EtdnbhyXq9S3VJnyXTbC/m5BVtw102ijmq5jzg=,iv:v7ehlAbzxsb3LKQM42YKIgb25vRrjjCMb51LYa36aQA=,tag:a13OnrrkLljdROb3uqq1KA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
